FROM continuumio/anaconda:5.2.0

RUN apt-get install -y vim
RUN conda install -y -c conda-forge gdal=2.2.4
RUN conda install -y -c conda-forge cartopy
RUN conda install -y -c conda-forge ncurses 
RUN conda install -y -c conda-forge future
