name: oco_vistool
channels:
  - conda-forge
dependencies:
  - python=3
  - satpy=0.53.0
  - netcdf4=1.7.1
  - h5py=3.12.1
  - matplotlib=3.9.2
  - pandas=2.2.3
  - cartopy=0.24.0
  - owslib=0.32.0
  - boto3=1.35.67
